### ISSUE TITLE
/info 지원 트랙 옵션 placeholder 필요

### ISSUE THREAD

**Issue by dianexjeong** [Applion-11th/Applion-Client#44]
현재 `/info`에서 `지원 트랙` 필드의 default 값이 백앤드로 표시되고 있습니다!
`const [selected, setSelected] = useState("지원하실 트랙을 선택해주세요");`
의 useState 초기값이 적용되지 않는 것으로 보입니다

**Comment by chxxrin** [comment]
placeholder 해결했습니다.
