### ISSUE TITLE
로그인 실패의 다양한 error code 별로 알림

### ISSUE THREAD

**Issue by dianexjeong** [Applion-11th/Applion-Client#68]
현재는
- 사용자 정보가 일치하지 않는 경우 (username / pw 불일치) 에만 경고 메세지를 보내고 있습니다
- textarea가 입력되었음에도.. 이전에 언급했던 #43 등의 이유로 필드가 채워지지 않았다고 인식해서 에러를 보내는 경우도 있어서
- 이러한 상황에 대한 안내 멘트나 #43이 발생하지 않도록 하는 리팩토링이 필요해 보입니다!

**Comment by chxxrin** [comment]
제 생각에는 사용자 정보가 일치하지 않는 경우가 로그인 실패의 에러라고 생각하는데 혹시 다른 에러가 있을까요?
#43번 에러는 고쳐서 오류가 나진 않습니다.

**Comment by dianexjeong** [comment]
@chxxrin 아하!!!! 그러면 해결된 것 같아요 감사합니다~!
